data:
  path: '/home/vladbakhteev/data/aorta'
  repeat_dataset: 2000
  width: 320

train:
  n_gpu: 1
  batch_size: 32
  num_workers: 32
  num_epochs: 50


model:
  name: 'linknet'
  dims: 2
  params:
    encoder_name: 'efficientnet-b0'
    encoder_depth: 5
    encoder_weights: 'imagenet'
    in_channels: 3
    classes: 1


scheduler:
  name: 'cosine_restarts'
  params:
    T_0: 2
    T_mult: 2


optimizer:
  name: 'adam'
  params:
    lr: 0.001


criterion:
  name: 'joint'
  params:

    first:
      name: 'dice'
      weight: 2
      params:
        mode: 'binary'

    second:
      name: 'focal'
      weight: 1
      params:
        alpha: 0.05
        gamma: 2